apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: customer
  name: customer
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: customer
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: customer
  name: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: customer
    spec:
      containers:
      - image: istiodemo/customer:0.0.1-SNAPSHOT
        name: customer
        ports:
        - containerPort: 8080
        resources: {}
status: {}
